<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\Post;
use App\DTO\Cart\CartAddLineInput;
use App\DTO\Cart\CartDetailsOutput;
use App\Entity\Enum\CartStatus;
use App\Entity\Impl\AbstractEntity;
use App\Repository\CartRepository;
use App\State\Cart\CartAddLineProcessor;
use App\State\Cart\CartCollectionProvider;
use App\State\Cart\CartOpenProcessor;
use App\State\Cart\CartProvider;
use App\State\Cart\CartRemoveLineProcessor;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;
use ApiPlatform\OpenApi\Model\Operation as OpenApiOperation;
use App\DTO\Cart\CartPayInput;
use App\DTO\Cart\CartPayOutput;
use App\State\Cart\CartPayProcessor;

#[ApiResource(operations: [
    new Post(
        uriTemplate: '/carts',
        // le contrat n'envoie aucun corps sur cette adresse : il n'y a rien à désérialiser
        input: false,
        output: CartDetailsOutput::class,
        processor: CartOpenProcessor::class,
        // toutes les opérations du panier exigent un jeton, comme `/users/me` à l'étape 5
        security: "is_granted('ROLE_USER')",
    ),
    new GetCollection(
        uriTemplate: '/carts',
        paginationClientEnabled: false,
        output: CartDetailsOutput::class,
        provider: CartCollectionProvider::class,
        security: "is_granted('ROLE_USER')",
    ),
    new Post(
        uriTemplate: '/carts/{id}/items',
        uriVariables:[
            'id' => new Link(schema: [
                'type' => 'string',
                'format' => 'uuid',
            ])
        ],
        input: CartAddLineInput::class,
        output: CartDetailsOutput::class,
        provider: CartProvider::class,
        processor: CartAddLineProcessor::class,
        // le rendez-vous suivant explique cette ligne et la met à l'épreuve
        security: "object.getCreatedBy() == user",
        openapi: new OpenApiOperation(
            summary: 'Adds a line to the cart',
        )
    ),
    new Delete(
        uriTemplate: '/carts/{id}/items/{itemId}',
        uriVariables: [
            'id' => new Link(schema: [
                'type' => 'string',
                'format' => 'uuid',
            ]),
            'itemId' => new Link(schema: [
                'fromClass' => CartItem::class,
                'fromProperty' => 'id',
                'type' => 'string',
                'format' => 'uuid',
            ]),
        ],
        provider: CartProvider::class,
        processor: CartRemoveLineProcessor::class,
        security: "object.getCreatedBy() == user",
        openapi: new OpenApiOperation(
            summary: 'Removes a line from the cart',
        ),
    ),
    new Post(
        uriTemplate: '/carts/{id}/pay',
        input: CartPayInput::class,
        output: CartPayOutput::class,
        provider: CartProvider::class,
        processor: CartPayProcessor::class,
        security: "object.getCreatedBy() == user",
        status: 200,
    ),
])]
#[ORM\Entity(repositoryClass: CartRepository::class)]
#[ApiResource(operations: [
])]
class Cart extends AbstractEntity
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    private Uuid $id;

    #[ORM\Column(enumType: CartStatus::class)]
    private CartStatus $status = CartStatus::Pending;

    /**
     * @var Collection<int, CartItem>
     */
    #[ORM\OneToMany(
        mappedBy: 'cart',
        targetEntity: CartItem::class,
        cascade: ['persist'],
        orphanRemoval: false,
    )]
    private Collection $items;

    /**
     * Builds an empty pending cart with a time-ordered UUID, generated by the entity itself.
     */
    public function __construct()
    {
        $this->id = Uuid::v7();
        $this->items = new ArrayCollection();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getStatus(): CartStatus
    {
        return $this->status;
    }

    public function setStatus(CartStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, CartItem>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    /**
     * Attaches an item to this cart, and points the item back to it.
     */
    public function addItem(CartItem $item): static
    {
        $this->items->add($item);
        $item->setCart($this);

        return $this;
    }
}
