<?php

namespace App\Entity;

use App\Entity\Enum\CatapultModel;
use App\Entity\Impl\AbstractEntity;
use App\Repository\TripRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: TripRepository::class)]
class Trip extends AbstractEntity
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    private Uuid $id;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'origin_city_id', nullable: false)]
    private ?City $origin = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'destination_city_id', nullable: false)]
    private ?City $destination = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $departureAt = null;

    /**
     * Flight duration, in minutes.
     */
    #[ORM\Column]
    private ?int $duration = null;

    /**
     * Seat price, in cents.
     */
    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(enumType: CatapultModel::class)]
    private ?CatapultModel $catapultModel = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $boardingInfo = null;

    /**
     * Builds a trip with a time-ordered UUID, generated by the entity itself.
     */
    public function __construct()
    {
        $this->id = Uuid::v7();
    }

    /**
     * @return Uuid
     */
    public function getId(): Uuid
    {
        return $this->id;
    }

    /**
     * @return City|null
     */
    public function getOrigin(): ?City
    {
        return $this->origin;
    }

    /**
     * @param City|null $origin
     * @return $this
     */
    public function setOrigin(?City $origin): static
    {
        $this->origin = $origin;

        return $this;
    }

    /**
     * @return City|null
     */
    public function getDestination(): ?City
    {
        return $this->destination;
    }

    /**
     * @param City|null $destination
     * @return $this
     */
    public function setDestination(?City $destination): static
    {
        $this->destination = $destination;

        return $this;
    }

    /**
     * @return \DateTimeImmutable|null
     */
    public function getDepartureAt(): ?\DateTimeImmutable
    {
        return $this->departureAt;
    }

    /**
     * @param \DateTimeImmutable $departureAt
     * @return $this
     */
    public function setDepartureAt(\DateTimeImmutable $departureAt): static
    {
        $this->departureAt = $departureAt;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getDuration(): ?int
    {
        return $this->duration;
    }

    /**
     * @param int $duration
     * @return $this
     */
    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * @param int $price
     * @return $this
     */
    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return CatapultModel|null
     */
    public function getCatapultModel(): ?CatapultModel
    {
        return $this->catapultModel;
    }

    /**
     * @param CatapultModel $catapultModel
     * @return $this
     */
    public function setCatapultModel(CatapultModel $catapultModel): static
    {
        $this->catapultModel = $catapultModel;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getBoardingInfo(): ?string
    {
        return $this->boardingInfo;
    }

    /**
     * @param string $boardingInfo
     * @return $this
     */
    public function setBoardingInfo(string $boardingInfo): static
    {
        $this->boardingInfo = $boardingInfo;

        return $this;
    }
}
