<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Post;
use App\DTO\Trip\TripListOutput;
use App\DTO\Trip\TripSearchInput;
use App\Entity\Enum\CatapultModel;
use App\Entity\Impl\AbstractEntity;
use App\Repository\TripRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;
use ApiPlatform\OpenApi\Model\Operation as OpenApiOperation;
use App\State\Trip\TripSearchProcessor;
use ApiPlatform\OpenApi\Model\Response as OpenApiResponse;
use App\DTO\Trip\TripDetailsOutput;
use ApiPlatform\Metadata\Get;
use App\State\Trip\TripItemProvider;

#[ApiResource(operations: [
    new Post(
        uriTemplate: '/trips/search',
        // un Post répond 201 par défaut : cette recherche ne crée rien, le contrat n'y déclare qu'un 200
        status: 200,
        input: TripSearchInput::class,
        output: TripListOutput::class,
        processor: TripSearchProcessor::class,
        // on cherche un lancer sans être connecté : le contrat déclare l'opération publique
        openapi: new OpenApiOperation(
            security: [],
            // le générateur déduit la réponse du `output:`, qui nomme une classe et non un tableau :
            // il annonce un objet unique là où l'API rend une liste. On corrige la documentation.
            responses: ['200' => new OpenApiResponse(
                description: 'Les lancers disponibles',
                content: new \ArrayObject(['application/json' => ['schema' => [
                    'type' => 'array',
                    // le nom relevé au point 3, pas celui que le contrat écrit
                    'items' => ['$ref' => '#/components/schemas/Trip.TripListOutput'],
                ]]]),
            )],
        ),
    ),
    new Get(
        uriTemplate: '/trips/{id}',
        output: TripDetailsOutput::class,
        provider: TripItemProvider::class,
        // on consulte un lancer sans être connecté : le contrat déclare l'opération publique
        openapi: new OpenApiOperation(security: []),
    ),
])]
#[ORM\Entity(repositoryClass: TripRepository::class)]
class Trip extends AbstractEntity
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    private Uuid $id;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'origin_city_id', nullable: false)]
    private ?City $origin = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'destination_city_id', nullable: false)]
    private ?City $destination = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $departureAt = null;

    /**
     * Flight duration, in minutes.
     */
    #[ORM\Column]
    private ?int $duration = null;

    /**
     * Seat price, in cents.
     */
    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(enumType: CatapultModel::class)]
    private ?CatapultModel $catapultModel = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $boardingInfo = null;

    /**
     * Builds a trip with a time-ordered UUID, generated by the entity itself.
     */
    public function __construct()
    {
        $this->id = Uuid::v7();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getOrigin(): ?City
    {
        return $this->origin;
    }

    public function setOrigin(?City $origin): static
    {
        $this->origin = $origin;

        return $this;
    }

    public function getDestination(): ?City
    {
        return $this->destination;
    }

    public function setDestination(?City $destination): static
    {
        $this->destination = $destination;

        return $this;
    }

    public function getDepartureAt(): ?\DateTimeImmutable
    {
        return $this->departureAt;
    }


    public function setDepartureAt(\DateTimeImmutable $departureAt): static
    {
        $this->departureAt = $departureAt;

        return $this;
    }


    public function getDuration(): ?int
    {
        return $this->duration;
    }


    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }


    public function getPrice(): ?int
    {
        return $this->price;
    }


    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }


    public function getCatapultModel(): ?CatapultModel
    {
        return $this->catapultModel;
    }


    public function setCatapultModel(CatapultModel $catapultModel): static
    {
        $this->catapultModel = $catapultModel;

        return $this;
    }


    public function getBoardingInfo(): ?string
    {
        return $this->boardingInfo;
    }


    public function setBoardingInfo(string $boardingInfo): static
    {
        $this->boardingInfo = $boardingInfo;

        return $this;
    }
}
